services:
  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/static:/usr/share/nginx/html:ro
    depends_on:
      - backend

  backend:
    build: ./app
    container_name: alumnos-app-backend
    restart: always
    expose:
      - "5000"
    environment:
      DB_HOST: db
      DB_NAME: escuela
      DB_USER: admin
      DB_PASS: admin123

  db:
    image: postgres:13
    container_name: alumnos-app-db
    restart: always
    environment:
      POSTGRES_DB: escuela
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
